default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: git_sleep_development

test: &test
  <<: *default
  database: git_sleep_test

production:
  <<: *default
  database: git_sleep_production
